### PR TITLE
Added json file translation

### PR DESCRIPTION
**Pull request by 360NENZ**
Added json file translation

### CODE REVIEW

**Comment by KiminaNatsuki** [comment]
bro it's still under requested change @Arikatsu

**Comment by Arikatsu** [comment]
It's translation

**Comment by KiminaNatsuki** [comment]
> It's translation

image

**Comment by Arikatsu** [comment]
Bruh mobile github didn't show that 💀

**Comment by 360NENZ** [comment]
sorry,it's fixed in #4

**Pull request merged**
