### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by GanyusRightThigh**
cause im an idiot

### CODE REVIEW

**Comment by lunaticwhat** [comment]
spaghetti typo

**Comment by GanyusRightThigh** [comment]
> spaghetti typo

Yeah its like i spell dit me as dit mae, very sad typo

**Comment by lunaticwhat** [comment]
> > spaghetti typo
> 
> Yeah its like i spell dit me as dit mae, very sad typo

mae sounds cute actually

**Comment by GanyusRightThigh** [comment]
> > > spaghetti typo
> > 
> > 
> > Yeah its like i spell dit me as dit mae, very sad typo
> 
> mae sounds cute actually

How to pronounce mae

**Pull request merged**
